// CONFIGURATION DE L'APPLICATION (À METTRE À JOUR UNE SEULE FOIS)
const CONFIG = {
    SECRET_PASSWORD: "2227", 
    SUPABASE_URL: "https://ybxpjhcmhyycvousuepw.supabase.co", 
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlieHBqaGNtaHl5Y3ZvdXN1ZXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MTA5MzQsImV4cCI6MjA5NTE4NjkzNH0.JWOTI763oWDm8W_48kqvsbslgcMT98nrUoKLTYf53JY"
};
